project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: false
download_translations_args: '--all --skip-untranslated-strings'
files:
  - source: src/NeatNoter/NeatNoter/Resource/source/NeatNoter_Localizable.json
    translation: src/NeatNoter/NeatNoter/Resource/translation/%two_letters_code%.json